jobs:
  - name: aarch64-python-test
    type: runSh
    runtime:
     nodePool: custom__aarch64__Ubuntu_16_04 
    steps:
      - TASK:
          runtime:
            options:
              imageName: "drydock/aarch64_u16pytall"
              imageTag: master
          script:
         
            - python --version
            - python3.5 --version
            - pip --version
            - virtualenv --version
